{"name": "Проверка ручки логина под существующим пользователем - позитивная", "status": "passed", "description": "Проверяем, что под существующим пользователем можно залогиниться, возвращаются правивльные код и текст ответа", "start": 1714711901778, "stop": 1714711902109, "uuid": "91781f13-5a95-4ada-a8ff-449e607228ec", "historyId": "dded76a9971fcd45d1b4eae0a2de4bb8", "testCaseId": "dded76a9971fcd45d1b4eae0a2de4bb8", "fullName": "tests.user.test_user_login.TestUserLogin#test_user_login", "labels": [{"name": "parentSuite", "value": "tests.user"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DAPIA-UB"}, {"name": "thread", "value": "1288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.user.test_user_login"}]}