{"name": "Проверка ручки логина под пользователем с неверными логином и паролем пользователя - негативная", "status": "passed", "description": "Проверяем, что нельзя залогиниться пользователем с неверными логином и паролем, и что при этом возвращается ошибка, возвращаются правильные код и текст ответа", "start": 1714711902881, "stop": 1714711903167, "uuid": "75ae621d-0807-45b3-9f16-6ac159ca97f0", "historyId": "00963030759d48d5b27a02ab755a5bfc", "testCaseId": "00963030759d48d5b27a02ab755a5bfc", "fullName": "tests.user.test_user_login.TestUserLogin#test_user_login_with_incorrect_data", "labels": [{"name": "parentSuite", "value": "tests.user"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DAPIA-UB"}, {"name": "thread", "value": "1288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.user.test_user_login"}]}